# Position in local NED frame
float32 x				# North position in NED earth-fixed frame, (metres)
float32 y				# East position in NED earth-fixed frame, (metres)
float32 z				# Down position (negative altitude) in NED earth-fixed frame, (metres)

float32 roll
float32 pitch
float32 yaw

float32 x_gps
float32 y_gps
float32 z_gps

float32 a
float32 b
float32 c
float32 d
float32 e
float32 f
float32 g
float32 h
float32 i
float32 j

float32[4] q

# TOPICS exogenous_kalman
